#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
python3 - <<'PY'
from pathlib import Path
import re
p=Path('app/src/main/assets/index.html')
s=p.read_text()
s=re.sub(r'<div id="brand">LakeNav WI <span class="versionPill">v0\.\d+</span></div>', '<div id="brand">LakeNav WI <span class="versionPill">v0.22</span></div>', s, count=1)
s=s.replace("  let depthShadeRequest = 0;\n  let depthShadeTimer = null;", "  let depthShadeRequest = 0;\n  let depthShadeTimer = null;\n  let depthDataCoverage = null;\n  let depthDataZoomBand = null;\n  let depthLastFetch = 0;\n  let appPageVisible = document.visibilityState !== 'hidden';\n  let last3dDynamicSync = 0;")
s=s.replace("    map.on('moveend zoomend', scheduleDepthShadeRefresh);\n    map.on('moveend zoomend', scheduleWindRefresh);\n    map.on('moveend zoomend', scheduleWaveRefresh);\n    map.on('moveend zoomend', () => { if (lightningEnabled) scheduleLightningRefresh(); });", "    map.on('moveend', scheduleDepthShadeRefresh);\n    map.on('moveend', scheduleWindRefresh);\n    map.on('moveend', scheduleWaveRefresh);\n    map.on('moveend', () => { if (lightningEnabled) scheduleLightningRefresh(); });")
old="""  function sync3dNavigationData() {\n    if (!map3d || !map3dLoaded) return;\n    const setData=(id,data)=>{ const src=map3d.getSource(id); if(src&&src.setData) src.setData(data); };\n    const track = trackPoints.length>1 ? {type:'FeatureCollection',features:[{type:'Feature',properties:{},geometry:{type:'LineString',coordinates:trackPoints.map(p=>[Number(p.lon),Number(p.lat)])}}]} : emptyFeatureCollection();\n    setData('lakenav-track',track);\n    let routePts=[];\n    if (routeDrawMode && routeDrawPoints.length) routePts=routeDrawPoints.map(p=>({lat:Number(p.lat),lon:Number(p.lon)}));\n    else if (activeRouteId) routePts=routeWaypoints(routes.find(r=>r.id===activeRouteId));\n    const routeFc = routePts.length>1 ? {type:'FeatureCollection',features:[{type:'Feature',properties:{},geometry:{type:'LineString',coordinates:routePts.map(p=>[p.lon,p.lat])}}]} : emptyFeatureCollection();\n    setData('lakenav-route',routeFc);\n    const target=currentNavigationTarget();\n    const navFc = currentLoc && target ? {type:'FeatureCollection',features:[{type:'Feature',properties:{},geometry:{type:'LineString',coordinates:[[currentLoc.lon,currentLoc.lat],[target.lon,target.lat]]}}]} : emptyFeatureCollection();\n    setData('lakenav-nav',navFc);\n    const pts=[];\n    waypoints.forEach(w=>pts.push({type:'Feature',properties:{kind:w.type==='mob'?'mob':'waypoint'},geometry:{type:'Point',coordinates:[Number(w.lon),Number(w.lat)]}}));\n    routePts.forEach(p=>pts.push({type:'Feature',properties:{kind:'route'},geometry:{type:'Point',coordinates:[Number(p.lon),Number(p.lat)]}}));\n    setData('lakenav-points',{type:'FeatureCollection',features:pts});\n  }\n"""
new="""  function sync3dDynamicNavigation(force) {\n    if (!map3d || !map3dLoaded) return;\n    const now=performance.now();\n    if (!force && now-last3dDynamicSync < 180) return;\n    last3dDynamicSync=now;\n    const src=map3d.getSource('lakenav-nav');\n    if (!src || !src.setData) return;\n    const target=currentNavigationTarget();\n    const navFc=currentLoc && target ? {type:'FeatureCollection',features:[{type:'Feature',properties:{},geometry:{type:'LineString',coordinates:[[currentLoc.lon,currentLoc.lat],[target.lon,target.lat]]}}]} : emptyFeatureCollection();\n    try { src.setData(navFc); } catch(e) {}\n  }\n\n  function sync3dNavigationData() {\n    if (!map3d || !map3dLoaded) return;\n    const setData=(id,data)=>{ const src=map3d.getSource(id); if(src&&src.setData) { try { src.setData(data); } catch(e) {} } };\n    const track = trackPoints.length>1 ? {type:'FeatureCollection',features:[{type:'Feature',properties:{},geometry:{type:'LineString',coordinates:trackPoints.map(p=>[Number(p.lon),Number(p.lat)])}}]} : emptyFeatureCollection();\n    setData('lakenav-track',track);\n    let routePts=[];\n    if (routeDrawMode && routeDrawPoints.length) routePts=routeDrawPoints.map(p=>({lat:Number(p.lat),lon:Number(p.lon)}));\n    else if (activeRouteId) routePts=routeWaypoints(routes.find(r=>r.id===activeRouteId));\n    const routeFc = routePts.length>1 ? {type:'FeatureCollection',features:[{type:'Feature',properties:{},geometry:{type:'LineString',coordinates:routePts.map(p=>[p.lon,p.lat])}}]} : emptyFeatureCollection();\n    setData('lakenav-route',routeFc);\n    const pts=[];\n    waypoints.forEach(w=>pts.push({type:'Feature',properties:{kind:w.type==='mob'?'mob':'waypoint'},geometry:{type:'Point',coordinates:[Number(w.lon),Number(w.lat)]}}));\n    routePts.forEach(p=>pts.push({type:'Feature',properties:{kind:'route'},geometry:{type:'Point',coordinates:[Number(p.lon),Number(p.lat)]}}));\n    setData('lakenav-points',{type:'FeatureCollection',features:pts});\n    sync3dDynamicNavigation(true);\n  }\n"""
if old not in s: raise SystemExit('sync3dNavigationData block not found')
s=s.replace(old,new,1)
s=s.replace("  function updateNavigation() {\n    sync3dNavigationData();", "  function updateNavigation() {\n    sync3dDynamicNavigation();", 1)
s=s.replace("    updateHeadingVisuals();\n    sync3dBoat();\n    sync3dNavigationData();", "    updateHeadingVisuals();\n    sync3dBoat();", 1)
s=s.replace("    renderOfflineFallbackOverlays();\n    updateNavigation();", "    renderOfflineFallbackOverlays();\n    sync3dNavigationData();\n    updateNavigation();", 1)
pat=r"  function updateStormRadiusRing\(\) \{.*?\n  \}\n\n  function scheduleStormMonitor"
rep="""  function updateStormRadiusRing() {\n    if (!map) return;\n    if (!stormAlertsEnabled || !currentLoc) {\n      if (stormRadiusLayer) { try { map.removeLayer(stormRadiusLayer); } catch(e) {} stormRadiusLayer=null; }\n      $('stormAlertChip').style.display='none'; return;\n    }\n    const ll=[currentLoc.lat,currentLoc.lon], radius=milesToMeters(stormRadiusMiles);\n    if (!stormRadiusLayer) {\n      stormRadiusLayer=L.circle(ll,{radius,color:'#e67e22',weight:1.5,opacity:.65,dashArray:'7 7',fill:false,interactive:false}).addTo(map);\n    } else {\n      try { stormRadiusLayer.setLatLng(ll); stormRadiusLayer.setRadius(radius); } catch(e) {}\n    }\n  }\n\n  function scheduleStormMonitor"""
s,n=re.subn(pat,rep,s,count=1,flags=re.S)
if n!=1: raise SystemExit('storm ring block not found')
pat=r"  function updateLightningRadiusRing\(\) \{.*?\n  \}\n\n  function scheduleLightningRefresh"
rep="""  function updateLightningRadiusRing() {\n    if (!map) return;\n    if ((!lightningEnabled && !liveLightningEnabled) || !currentLoc) {\n      if (lightningRadiusLayer) { try { map.removeLayer(lightningRadiusLayer); } catch(e) {} lightningRadiusLayer=null; }\n      return;\n    }\n    const ll=[currentLoc.lat,currentLoc.lon], radius=milesToMeters(lightningRadiusMiles);\n    if (!lightningRadiusLayer) {\n      lightningRadiusLayer=L.circle(ll,{pane:'lightningPane',radius,color:'#8e44ad',weight:1.4,opacity:.65,dashArray:'4 7',fill:false,interactive:false}).addTo(map);\n    } else {\n      try { lightningRadiusLayer.setLatLng(ll); lightningRadiusLayer.setRadius(radius); } catch(e) {}\n    }\n  }\n\n  function scheduleLightningRefresh"""
s,n=re.subn(pat,rep,s,count=1,flags=re.S)
if n!=1: raise SystemExit('lightning ring block not found')
s=s.replace("  let lightningLastFetch = 0;", "  let lightningLastFetch = 0;\n  let lightningRefreshTimer = null;")
s=s.replace("  function scheduleLightningRefresh(force) {\n    if (!lightningEnabled || offlineMode) return;\n    setTimeout(()=>loadLightningRisk(!!force),500);\n  }", "  function scheduleLightningRefresh(force) {\n    if (!lightningEnabled || offlineMode) return;\n    clearTimeout(lightningRefreshTimer);\n    lightningRefreshTimer=setTimeout(()=>loadLightningRisk(!!force),650);\n  }")
needle="""    const span=Math.max(Math.abs(b.east-b.west),Math.abs(b.north-b.south));\n    if (span > 6 || viewZoom < 7) {"""
insert="""    const span=Math.max(Math.abs(b.east-b.west),Math.abs(b.north-b.south));\n    const zoomBand=viewZoom>=14?14:(viewZoom>=11?11:(viewZoom>=8?8:7));\n    const rawInsideCached = depthDataCoverage && raw.getWest()>=depthDataCoverage.west && raw.getEast()<=depthDataCoverage.east && raw.getSouth()>=depthDataCoverage.south && raw.getNorth()<=depthDataCoverage.north;\n    if (rawInsideCached && depthDataZoomBand===zoomBand && Date.now()-depthLastFetch < 3*60*1000 && latestDepthGeojson && latestDepthGeojson.features && latestDepthGeojson.features.length) {\n      if (mapMode==='3d') sync3dDepthData();\n      return;\n    }\n    if (span > 6 || viewZoom < 7) {"""
if needle not in s: raise SystemExit('depth span needle not found')
s=s.replace(needle,insert,1)
s=s.replace("    latestDepthGeojson=geojson;\n    sync3dDepthData();", "    latestDepthGeojson=geojson;\n    depthDataCoverage={west:b.west,east:b.east,south:b.south,north:b.north};\n    depthDataZoomBand=zoomBand;\n    depthLastFetch=Date.now();\n    sync3dDepthData();",1)
s=s.replace("    let last = performance.now();\n    const frame = now => {\n      if (!windEnabled) return;", "    let last = performance.now();\n    let lastPaint = 0;\n    const frame = now => {\n      if (!windEnabled) return;\n      if (!appPageVisible || mapMode !== '2d') { windAnimationFrame=requestAnimationFrame(frame); return; }\n      if (now-lastPaint < 32) { windAnimationFrame=requestAnimationFrame(frame); return; }\n      lastPaint=now;",1)
s=s.replace("const dpr = Math.max(1, Math.min(2, window.devicePixelRatio || 1));", "const dpr = Math.max(1, Math.min(1.6, window.devicePixelRatio || 1));",1)
s=s.replace("const chosen=past.slice(-8).map", "const chosen=past.slice(-6).map",1)
s=s.replace("radarAnimationTimer=setInterval(()=>showRadarFrame(radarFrameIndex+1),1100);", "radarAnimationTimer=setInterval(()=>{ if(appPageVisible && mapMode==='2d') showRadarFrame(radarFrameIndex+1); },1350);",1)
marker="""  function syncMarineStatus(){\n    if(!$('quickMarineStatus')) return;\n    const on=[]; if(windEnabled) on.push('Wind'); if(waveEnabled) on.push('Waves'); if(radarEnabled) on.push('Radar');\n    $('quickMarineStatus').textContent=on.length?on.join(' + ')+' active.':'Wave height and radar are off.';\n  }\n"""
extra=marker+"""\n  document.addEventListener('visibilitychange', () => {\n    appPageVisible=document.visibilityState!=='hidden';\n    if (!appPageVisible) {\n      cancelAnimationFrame(windAnimationFrame); windAnimationFrame=0;\n      clearInterval(radarAnimationTimer); radarAnimationTimer=null;\n      return;\n    }\n    if (windEnabled && !offlineMode) animateWind();\n    if (waveEnabled) drawWaveOverlay();\n    if (radarEnabled && radarFrames.length) { showRadarFrame(radarFrameIndex); startRadarAnimation(); }\n    if (mapMode==='3d' && map3d) { try { map3d.resize(); } catch(e) {} }\n  });\n"""
if marker not in s: raise SystemExit('marine status marker not found')
s=s.replace(marker,extra,1)
s=s.replace("      if (!silent && window.Android && Android.toast) Android.toast('3D chart preview enabled');", "      cancelAnimationFrame(windAnimationFrame); windAnimationFrame=0;\n      if (!silent && window.Android && Android.toast) Android.toast('3D chart preview enabled');",1)
s=s.replace("      applyMapOrientation();\n      if (map) setTimeout", "      applyMapOrientation();\n      if (windEnabled && appPageVisible && !offlineMode) animateWind();\n      if (waveEnabled) drawWaveOverlay();\n      if (map) setTimeout",1)
p.write_text(s)

rp=Path('README.md')
r=rp.read_text()
if '## Version 0.22 features' not in r:
    insert='''\n## Version 0.22 features\n\n### Refinement and performance pass\n- Removes duplicate layer-refresh scheduling after map zoom gestures and debounces modeled-lightning refreshes.\n- Reuses the padded NOAA ENC depth area already in memory during small 3D pans/zooms for up to three minutes, while still recalculating zoom-aware labels. This reduces repeated multi-source depth downloads.\n- Separates the frequently changing 3D navigation-to-target line from static waypoints, routes, and track geometry so every GPS fix no longer rebuilds every 3D navigation source.\n- Reuses storm and lightning radius circles as GPS moves instead of deleting and recreating Leaflet layers each fix.\n- Caps animated wind drawing near 30 fps, reduces high-DPI canvas load, pauses continuous animation when LakeNav is backgrounded or when 3D mode is active, and restores it cleanly on return.\n- Radar now loops six recent frames at a slightly calmer cadence and pauses tile-frame swapping while the app is backgrounded or 3D mode is active.\n- No feature removals: routes, MOB, weather monitoring, 2D/3D charts, offline lakes, waypoints, tracks, and existing depth behavior remain available.\n'''
    pos=r.find('\n## Version 0.21 features')
    if pos<0: pos=0
    r=r[:pos]+insert+r[pos:]
rp.write_text(r)
PY
sed -i "s/versionCode [0-9][0-9]*/versionCode 22/" app/build.gradle
sed -i "s/versionName '[^']*'/versionName '0.22.0'/" app/build.gradle
grep -q 'v0.22' app/src/main/assets/index.html
grep -q 'Refinement and performance pass' README.md
printf 'LakeNav WI v0.22 refinement/performance pass applied.\n'
